import {stripIndent} from 'common-tags'
import camelCase from 'lodash.camelcase'
import {z} from 'zod'

import {ZodToTypescriptMapper, type ZodToTypescriptMapperTarget} from '../language-mappers/zod-to-typescript-mapper.js'
import {ZodToTypescriptReturnValueMapper} from '../language-mappers/zod-to-typescript-return-value-mapper.js'
import {BaseTypescriptGenerator} from './base-typescript-generator.js'

export class ReactTypeScriptGenerator extends BaseTypescriptGenerator {
  get filename(): string {
    return 'prefab-client.ts'
  }

  protected durationTypeMap(): z.ZodTypeAny {
    return z.object({ms: z.number(), seconds: z.number()})
  }

  generate(): string {
    return stripIndent`
    /* eslint-disable */
    // AUTOGENERATED by prefab-cli's 'gen' command
    import { Prefab } from "@prefab-cloud/prefab-cloud-js"
    import { createPrefabHook } from "@prefab-cloud/prefab-cloud-react"
    ${this.additionalDependencies().join('\n') || '// No additional dependencies required'}

    declare namespace PrefabTypeGeneration {
      export type ReactHookConfigurationRaw = {
        ${this.generateSchemaTypes('raw').join('\n        ') || '// No types generated'}
      }

      export type ReactHookConfigurationAccessor = {
        ${this.generateSchemaTypes().join('\n        ') || '// No types generated'}
      }
    }

    export class PrefabTypesafeReact {
      constructor(private prefab: Prefab) { }

      get<K extends keyof PrefabTypeGeneration.ReactHookConfigurationRaw>(key: K): PrefabTypeGeneration.ReactHookConfigurationRaw[K] {
        return this.prefab.get(key) as PrefabTypeGeneration.ReactHookConfigurationRaw[K]
      }

      ${this.generateAccessorMethods().join('\n\n      ') || '// No methods generated'}
    }

    export const usePrefab = createPrefabHook(PrefabTypesafeReact)
    `
  }

  private additionalDependencies(): string[] {
    const dependencies: string[] = []
    const hasFunctions = this.filteredConfigurations().some((c) => c.hasFunction)

    if (hasFunctions) {
      dependencies.push(this.MUSTACHE_IMPORT)
    }

    return dependencies
  }

  private filteredConfigurations() {
    return this.configurations().filter(
      (config) => config.configType === 'FEATURE_FLAG' || config.sendToClientSdk === true,
    )
  }

  private generateAccessorMethods(): string[] {
    const uniqueMethods: Record<string, string> = {}
    const schemaTypes = this.filteredConfigurations().map((config) => {
      let methodName = camelCase(config.key)

      // If the method name starts with a digit, prefix it with an underscore to ensure method name is valid
      if (/^\d/.test(methodName)) {
        methodName = `_${methodName}`
      }

      if (uniqueMethods[methodName]) {
        throw new Error(
          `Method '${methodName}' is already registered. Prefab key ${config.key} conflicts with '${uniqueMethods[methodName]}'!`,
        )
      }

      uniqueMethods[methodName] = config.key

      if (config.configType === 'FEATURE_FLAG') {
        return stripIndent`
          get ${methodName}(): boolean {
                  return this.prefab.isEnabled('${config.key}')
                }
          `
      }

      if (config.hasFunction) {
        const returnValue = new ZodToTypescriptReturnValueMapper().resolveType(config.schema)

        return stripIndent`
          ${methodName}(): PrefabTypeGeneration.ReactHookConfigurationAccessor['${config.key}'] {
                  const raw = this.get('${config.key}')
                  return ${returnValue}
                }
          `
      }

      return stripIndent`
        get ${methodName}(): PrefabTypeGeneration.ReactHookConfigurationAccessor['${config.key}'] {
                return this.get('${config.key}')
              }
        `
    })

    return schemaTypes
  }

  private generateSchemaTypes(target: ZodToTypescriptMapperTarget = 'accessor'): string[] {
    const schemaTypes = this.filteredConfigurations().map((config) => {
      const mapper = new ZodToTypescriptMapper({fieldName: config.key, target})

      return mapper.renderField(config.schema)
    })

    return schemaTypes
  }
}
