import {expect} from 'chai'
import {stripIndent} from 'common-tags'

import {NodeTypeScriptGenerator} from '../../../src/codegen/code-generators/node-typescript-generator.js'
import {type ConfigFile} from '../../../src/codegen/types.js'

const mockLog: (category: string | unknown, message?: unknown) => void = () => {}
const defaultMockConfigFile: ConfigFile = {
  configs: [],
}

describe('NodeTypeScriptGenerator', () => {
  describe('filename', () => {
    it('should return the correct filename', () => {
      const generator = new NodeTypeScriptGenerator({
        configFile: defaultMockConfigFile,
        log: mockLog,
      })

      expect(generator.filename).to.equal('prefab-server.ts')
    })
  })

  describe('generate', () => {
    it('should generate basic code structure when no configs exist', () => {
      const generator = new NodeTypeScriptGenerator({
        configFile: defaultMockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import {Prefab, Contexts} from '@prefab-cloud/prefab-cloud-node'
      // No additional dependencies required

      type ContextObj = Record<string, Record<string, unknown>>

      declare namespace PrefabTypeGeneration {
        export type NodeServerConfigurationRaw = {
          // No types generated
        }

        export type NodeServerConfigurationAccessor = {
          // No types generated
        }
      }

      export class PrefabTypesafeNode {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.NodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationRaw[K] {
          return this.prefab.get(key, contexts) as PrefabTypeGeneration.NodeServerConfigurationRaw[K]
        }

        // No methods generated
      }`)
    })

    it('should include Mustache import when function configs exist', () => {
      // Use mustache syntax for the template to ensure a function is generated
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'some-key',
            rows: [{values: [{value: {string: 'Hello, {{name}}!'}}]}],
            valueType: 'STRING',
          },
        ],
      }
      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      // Verify Mustache import is included
      expect(result).to.include("import Mustache from 'mustache'")
    })

    it('should generate type definitions for configs and feature flags, not schema, or empty configurations', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'CONFIG',
            key: 'emptyConfig',
            rows: [],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'flag1',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'emptyFlag',
            rows: [],
            valueType: 'BOOL',
          },
          {
            configType: 'SCHEMA',
            key: 'schema1',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import {Prefab, Contexts} from '@prefab-cloud/prefab-cloud-node'
      // No additional dependencies required

      type ContextObj = Record<string, Record<string, unknown>>

      declare namespace PrefabTypeGeneration {
        export type NodeServerConfigurationRaw = {
          "config1": string
          "flag1": boolean
        }

        export type NodeServerConfigurationAccessor = {
          "config1": string
          "flag1": boolean
        }
      }

      export class PrefabTypesafeNode {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.NodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationRaw[K] {
          return this.prefab.get(key, contexts) as PrefabTypeGeneration.NodeServerConfigurationRaw[K]
        }

        config1(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['config1'] {
          return this.get('config1', contexts)
        }

        flag1(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['flag1'] {
          return this.get('flag1', contexts)
        }
      }
      `)
    })

    it('should generate function accessor methods for function configs', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {string: 'Hello, {{name}}!'}}]}],
            valueType: 'STRING',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import {Prefab, Contexts} from '@prefab-cloud/prefab-cloud-node'
      import Mustache from 'mustache'

      type ContextObj = Record<string, Record<string, unknown>>

      declare namespace PrefabTypeGeneration {
        export type NodeServerConfigurationRaw = {
          "config1": string | undefined
        }

        export type NodeServerConfigurationAccessor = {
          "config1": (...params: [{ "name": string }]) => string
        }
      }

      export class PrefabTypesafeNode {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.NodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationRaw[K] {
          return this.prefab.get(key, contexts) as PrefabTypeGeneration.NodeServerConfigurationRaw[K]
        }

        config1(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['config1'] {
          const raw = this.get('config1', contexts)
          return (params) => Mustache.render(raw ?? "", params)
        }
      }
      `)
    })

    it('should generate durations correctly', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {int: 1}}]}],
            valueType: 'DURATION',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import {Prefab, Contexts} from '@prefab-cloud/prefab-cloud-node'
      // No additional dependencies required

      type ContextObj = Record<string, Record<string, unknown>>

      declare namespace PrefabTypeGeneration {
        export type NodeServerConfigurationRaw = {
          "config1": number
        }

        export type NodeServerConfigurationAccessor = {
          "config1": number
        }
      }

      export class PrefabTypesafeNode {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.NodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationRaw[K] {
          return this.prefab.get(key, contexts) as PrefabTypeGeneration.NodeServerConfigurationRaw[K]
        }

        config1(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['config1'] {
          return this.get('config1', contexts)
        }
      }
      `)
    })

    it('should prefix method names with underscore when they start with a digit', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: '1config',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: '1flag',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import {Prefab, Contexts} from '@prefab-cloud/prefab-cloud-node'
      // No additional dependencies required

      type ContextObj = Record<string, Record<string, unknown>>

      declare namespace PrefabTypeGeneration {
        export type NodeServerConfigurationRaw = {
          "1config": string
          "1flag": boolean
        }

        export type NodeServerConfigurationAccessor = {
          "1config": string
          "1flag": boolean
        }
      }

      export class PrefabTypesafeNode {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.NodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationRaw[K] {
          return this.prefab.get(key, contexts) as PrefabTypeGeneration.NodeServerConfigurationRaw[K]
        }

        _1Config(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['1config'] {
          return this.get('1config', contexts)
        }

        _1Flag(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['1flag'] {
          return this.get('1flag', contexts)
        }
      }
      `)
    })

    it('should properly camelCase various key formats', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'snake_case_key',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'kebab-case-key',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
          {
            configType: 'CONFIG',
            key: 'dot.notation.key',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'UPPER_CASE_KEY',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
          {
            configType: 'CONFIG',
            key: 'key_with_$_special',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'key/with/slashes',
            rows: [{values: [{value: {bool: true}}]}],
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import {Prefab, Contexts} from '@prefab-cloud/prefab-cloud-node'
      // No additional dependencies required

      type ContextObj = Record<string, Record<string, unknown>>

      declare namespace PrefabTypeGeneration {
        export type NodeServerConfigurationRaw = {
          "dot.notation.key": string
          "kebab-case-key": boolean
          "key_with_$_special": string
          "key/with/slashes": boolean
          "snake_case_key": string
          "UPPER_CASE_KEY": boolean
        }

        export type NodeServerConfigurationAccessor = {
          "dot.notation.key": string
          "kebab-case-key": boolean
          "key_with_$_special": string
          "key/with/slashes": boolean
          "snake_case_key": string
          "UPPER_CASE_KEY": boolean
        }
      }

      export class PrefabTypesafeNode {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.NodeServerConfigurationRaw>(key: K, contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationRaw[K] {
          return this.prefab.get(key, contexts) as PrefabTypeGeneration.NodeServerConfigurationRaw[K]
        }

        dotNotationKey(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['dot.notation.key'] {
          return this.get('dot.notation.key', contexts)
        }

        kebabCaseKey(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['kebab-case-key'] {
          return this.get('kebab-case-key', contexts)
        }

        keyWithSpecial(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['key_with_$_special'] {
          return this.get('key_with_$_special', contexts)
        }

        keyWithSlashes(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['key/with/slashes'] {
          return this.get('key/with/slashes', contexts)
        }

        snakeCaseKey(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['snake_case_key'] {
          return this.get('snake_case_key', contexts)
        }

        upperCaseKey(contexts?: Contexts | ContextObj): PrefabTypeGeneration.NodeServerConfigurationAccessor['UPPER_CASE_KEY'] {
          return this.get('UPPER_CASE_KEY', contexts)
        }
      }`)
    })

    it('should throw an error when method names conflict', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'keyWithSlashes',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
          {
            configType: 'CONFIG',
            key: 'key/with/slashes',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            valueType: 'STRING',
          },
        ],
      }

      const generator = new NodeTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      expect(() => generator.generate()).to.throw(
        "Method 'keyWithSlashes' is already registered. Prefab key keyWithSlashes conflicts with 'key/with/slashes'!",
      )
    })
  })
})
