import {expect} from 'chai'
import {stripIndent} from 'common-tags'

import {ReactTypeScriptGenerator} from '../../../src/codegen/code-generators/react-typescript-generator.js'
import {type ConfigFile} from '../../../src/codegen/types.js'

const mockLog: (category: string | unknown, message?: unknown) => void = () => {}
const defaultMockConfigFile: ConfigFile = {
  configs: [],
}

describe('ReactTypeScriptGenerator', () => {
  describe('filename', () => {
    it('should return the correct filename', () => {
      const generator = new ReactTypeScriptGenerator({
        configFile: defaultMockConfigFile,
        log: mockLog,
      })

      expect(generator.filename).to.equal('prefab-client.ts')
    })
  })

  describe('generate', () => {
    it('should generate basic code structure when no configs exist', () => {
      const generator = new ReactTypeScriptGenerator({
        configFile: defaultMockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import { Prefab } from "@prefab-cloud/prefab-cloud-js"
      import { createPrefabHook } from "@prefab-cloud/prefab-cloud-react"
      // No additional dependencies required

      declare namespace PrefabTypeGeneration {
        export type ReactHookConfigurationRaw = {
          // No types generated
        }

        export type ReactHookConfigurationAccessor = {
          // No types generated
        }
      }

      export class PrefabTypesafeReact {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.ReactHookConfigurationRaw>(key: K): PrefabTypeGeneration.ReactHookConfigurationRaw[K] {
          return this.prefab.get(key) as PrefabTypeGeneration.ReactHookConfigurationRaw[K]
        }

        // No methods generated
      }

      export const usePrefab = createPrefabHook(PrefabTypesafeReact)
      `)
    })

    it('should include Mustache import when function configs exist', () => {
      // Use mustache syntax for the template to ensure a function is generated
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'some-key',
            rows: [{values: [{value: {string: 'Hello, {{name}}!'}}]}],
            sendToClientSdk: true,
            valueType: 'STRING',
          },
        ],
      }
      const generator = new ReactTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      // Verify Mustache import is included
      expect(result).to.include("import Mustache from 'mustache'")
    })

    it('should generate type definitions for configs and feature flags, not schema, empty configurations, or non-client configs', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            sendToClientSdk: true,
            valueType: 'STRING',
          },
          {
            configType: 'CONFIG',
            key: 'emptyConfig',
            rows: [],
            sendToClientSdk: true,
            valueType: 'STRING',
          },
          {
            configType: 'CONFIG',
            key: 'nonClientConfig',
            rows: [],
            sendToClientSdk: false,
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'flag1',
            rows: [{values: [{value: {bool: true}}]}],
            sendToClientSdk: true,
            valueType: 'BOOL',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'emptyFlag',
            rows: [],
            sendToClientSdk: true,
            valueType: 'BOOL',
          },
          {
            configType: 'SCHEMA',
            key: 'schema1',
            rows: [{values: [{value: {bool: true}}]}],
            sendToClientSdk: true,
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new ReactTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import { Prefab } from "@prefab-cloud/prefab-cloud-js"
      import { createPrefabHook } from "@prefab-cloud/prefab-cloud-react"
      // No additional dependencies required

      declare namespace PrefabTypeGeneration {
        export type ReactHookConfigurationRaw = {
          "config1": string
          "flag1": boolean
        }

        export type ReactHookConfigurationAccessor = {
          "config1": string
          "flag1": boolean
        }
      }

      export class PrefabTypesafeReact {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.ReactHookConfigurationRaw>(key: K): PrefabTypeGeneration.ReactHookConfigurationRaw[K] {
          return this.prefab.get(key) as PrefabTypeGeneration.ReactHookConfigurationRaw[K]
        }

        get config1(): PrefabTypeGeneration.ReactHookConfigurationAccessor['config1'] {
          return this.get('config1')
        }

        get flag1(): boolean {
          return this.prefab.isEnabled('flag1')
        }
      }

      export const usePrefab = createPrefabHook(PrefabTypesafeReact)
      `)
    })

    it('should generate function accessor methods for function configs', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {string: 'Hello, {{name}}!'}}]}],
            sendToClientSdk: true,
            valueType: 'STRING',
          },
        ],
      }

      const generator = new ReactTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import { Prefab } from "@prefab-cloud/prefab-cloud-js"
      import { createPrefabHook } from "@prefab-cloud/prefab-cloud-react"
      import Mustache from 'mustache'

      declare namespace PrefabTypeGeneration {
        export type ReactHookConfigurationRaw = {
          "config1": string | undefined
        }

        export type ReactHookConfigurationAccessor = {
          "config1": (...params: [{ "name": string }]) => string
        }
      }

      export class PrefabTypesafeReact {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.ReactHookConfigurationRaw>(key: K): PrefabTypeGeneration.ReactHookConfigurationRaw[K] {
          return this.prefab.get(key) as PrefabTypeGeneration.ReactHookConfigurationRaw[K]
        }

        config1(): PrefabTypeGeneration.ReactHookConfigurationAccessor['config1'] {
          const raw = this.get('config1')
          return (params) => Mustache.render(raw ?? "", params)
        }
      }

      export const usePrefab = createPrefabHook(PrefabTypesafeReact)
      `)
    })

    it('should generate durations correctly', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'config1',
            rows: [{values: [{value: {int: 1}}]}],
            sendToClientSdk: true,
            valueType: 'DURATION',
          },
        ],
      }

      const generator = new ReactTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import { Prefab } from "@prefab-cloud/prefab-cloud-js"
      import { createPrefabHook } from "@prefab-cloud/prefab-cloud-react"
      // No additional dependencies required

      declare namespace PrefabTypeGeneration {
        export type ReactHookConfigurationRaw = {
          "config1": { "ms": number; "seconds": number }
        }

        export type ReactHookConfigurationAccessor = {
          "config1": { "ms": number; "seconds": number }
        }
      }

      export class PrefabTypesafeReact {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.ReactHookConfigurationRaw>(key: K): PrefabTypeGeneration.ReactHookConfigurationRaw[K] {
          return this.prefab.get(key) as PrefabTypeGeneration.ReactHookConfigurationRaw[K]
        }

        get config1(): PrefabTypeGeneration.ReactHookConfigurationAccessor['config1'] {
          return this.get('config1')
        }
      }

      export const usePrefab = createPrefabHook(PrefabTypesafeReact)
      `)
    })

    it('should prefix method names with underscore when they start with a digit', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: '1config',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            sendToClientSdk: true,
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: '1flag',
            rows: [{values: [{value: {bool: true}}]}],
            sendToClientSdk: true,
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new ReactTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import { Prefab } from "@prefab-cloud/prefab-cloud-js"
      import { createPrefabHook } from "@prefab-cloud/prefab-cloud-react"
      // No additional dependencies required

      declare namespace PrefabTypeGeneration {
        export type ReactHookConfigurationRaw = {
          "1config": string
          "1flag": boolean
        }

        export type ReactHookConfigurationAccessor = {
          "1config": string
          "1flag": boolean
        }
      }

      export class PrefabTypesafeReact {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.ReactHookConfigurationRaw>(key: K): PrefabTypeGeneration.ReactHookConfigurationRaw[K] {
          return this.prefab.get(key) as PrefabTypeGeneration.ReactHookConfigurationRaw[K]
        }

        get _1Config(): PrefabTypeGeneration.ReactHookConfigurationAccessor['1config'] {
          return this.get('1config')
        }

        get _1Flag(): boolean {
          return this.prefab.isEnabled('1flag')
        }
      }

      export const usePrefab = createPrefabHook(PrefabTypesafeReact)
      `)
    })

    it('should properly camelCase various key formats', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'snake_case_key',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            sendToClientSdk: true,
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'kebab-case-key',
            rows: [{values: [{value: {bool: true}}]}],
            sendToClientSdk: true,
            valueType: 'BOOL',
          },
          {
            configType: 'CONFIG',
            key: 'dot.notation.key',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            sendToClientSdk: true,
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'UPPER_CASE_KEY',
            rows: [{values: [{value: {bool: true}}]}],
            sendToClientSdk: true,
            valueType: 'BOOL',
          },
          {
            configType: 'CONFIG',
            key: 'key_with_$_special',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            sendToClientSdk: true,
            valueType: 'STRING',
          },
          {
            configType: 'FEATURE_FLAG',
            key: 'key/with/slashes',
            rows: [{values: [{value: {bool: true}}]}],
            sendToClientSdk: true,
            valueType: 'BOOL',
          },
        ],
      }

      const generator = new ReactTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      const result = generator.generate()

      expect(result).to.equal(stripIndent`
      // AUTOGENERATED by prefab-cli's 'gen' command
      import { Prefab } from "@prefab-cloud/prefab-cloud-js"
      import { createPrefabHook } from "@prefab-cloud/prefab-cloud-react"
      // No additional dependencies required

      declare namespace PrefabTypeGeneration {
        export type ReactHookConfigurationRaw = {
          "dot.notation.key": string
          "kebab-case-key": boolean
          "key_with_$_special": string
          "key/with/slashes": boolean
          "snake_case_key": string
          "UPPER_CASE_KEY": boolean
        }

        export type ReactHookConfigurationAccessor = {
          "dot.notation.key": string
          "kebab-case-key": boolean
          "key_with_$_special": string
          "key/with/slashes": boolean
          "snake_case_key": string
          "UPPER_CASE_KEY": boolean
        }
      }

      export class PrefabTypesafeReact {
        constructor(private prefab: Prefab) { }

        get<K extends keyof PrefabTypeGeneration.ReactHookConfigurationRaw>(key: K): PrefabTypeGeneration.ReactHookConfigurationRaw[K] {
          return this.prefab.get(key) as PrefabTypeGeneration.ReactHookConfigurationRaw[K]
        }

        get dotNotationKey(): PrefabTypeGeneration.ReactHookConfigurationAccessor['dot.notation.key'] {
          return this.get('dot.notation.key')
        }

        get kebabCaseKey(): boolean {
          return this.prefab.isEnabled('kebab-case-key')
        }

        get keyWithSpecial(): PrefabTypeGeneration.ReactHookConfigurationAccessor['key_with_$_special'] {
          return this.get('key_with_$_special')
        }

        get keyWithSlashes(): boolean {
          return this.prefab.isEnabled('key/with/slashes')
        }

        get snakeCaseKey(): PrefabTypeGeneration.ReactHookConfigurationAccessor['snake_case_key'] {
          return this.get('snake_case_key')
        }

        get upperCaseKey(): boolean {
          return this.prefab.isEnabled('UPPER_CASE_KEY')
        }
      }

      export const usePrefab = createPrefabHook(PrefabTypesafeReact)
      `)
    })

    it('should throw an error when method names conflict', () => {
      const mockConfigFile: ConfigFile = {
        configs: [
          {
            configType: 'CONFIG',
            key: 'keyWithSlashes',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            sendToClientSdk: true,
            valueType: 'STRING',
          },
          {
            configType: 'CONFIG',
            key: 'key/with/slashes',
            rows: [{values: [{value: {string: 'Some value'}}]}],
            sendToClientSdk: true,
            valueType: 'STRING',
          },
        ],
      }

      const generator = new ReactTypeScriptGenerator({
        configFile: mockConfigFile,
        log: mockLog,
      })

      expect(() => generator.generate()).to.throw(
        "Method 'keyWithSlashes' is already registered. Prefab key keyWithSlashes conflicts with 'key/with/slashes'!",
      )
    })
  })
})
