name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

# Note, this comes from https://github.com/oclif/github-workflows/blob/main/.github/workflows/unitTest.yml because I couldn't figure out how to make `env` work with the default content from oclif
#
# jobs:
#   unit-tests:
#     uses: oclif/github-workflows/.github/workflows/unitTest.yml@main
#
jobs:
  unit-tests:
    env:
      PREFAB_API_KEY: ${{ secrets.PREFAB_API_KEY }}
      PREFAB_CDN_URL: ${{ secrets.PREFAB_CDN_URL }}
      PREFAB_API_URL: ${{ secrets.PREFAB_API_URL }}
      PREFAB_ENCRYPTION_KEY_DEVELOPMENT: ${{ secrets.PREFAB_ENCRYPTION_KEY_DEVELOPMENT }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        node_version: [lts/-1, lts/*, latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - run: yarn install --network-timeout 600000
      - run: yarn build
      - run: yarn test:ci
